/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectpbo.view;

import projectpbo.view.panels.AdminRoomPanel;
import projectpbo.view.panels.SearchRoomPanel;
import projectpbo.view.panels.WelcomePanel;
import projectpbo.view.panels.AdminUserPanel;
import projectpbo.view.panels.MyReservationsPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;
/**
 *
 * @author User
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form NewJFrame
     */
    
    private JPanel mainPanel;
    private CardLayout cardLayout;

    public MainFrame() {
        initComponentsCustom();
    }
    
    private void initComponentsCustom() {
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Reservasi Hotel");
        setSize(800, 600);
        setLocationRelativeTo(null);

        javax.swing.JMenuBar menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu menuFile = new javax.swing.JMenu("File");
        javax.swing.JMenu menuNav = new javax.swing.JMenu("Reservasi");
        javax.swing.JMenu menuAkun = new javax.swing.JMenu("Akun");

        javax.swing.JMenuItem itemExit = new javax.swing.JMenuItem("Keluar");
        javax.swing.JMenuItem itemHome = new javax.swing.JMenuItem("Home / Dashboard");
        javax.swing.JMenuItem itemCari = new javax.swing.JMenuItem("Cari Kamar");
        javax.swing.JMenuItem itemRiwayat = new javax.swing.JMenuItem("Riwayat");
        javax.swing.JMenuItem itemLogout = new javax.swing.JMenuItem("Logout");

        itemExit.addActionListener(e -> System.exit(0));
        itemHome.addActionListener(e -> showWelcomePanel());
        itemCari.addActionListener(e -> showSearchPanel());
        itemRiwayat.addActionListener(e -> showHistoryPanel());
        itemLogout.addActionListener(e -> {
            new LoginFrame().setVisible(true);
            this.dispose();
        });

        menuAkun.add(itemLogout);
        menuFile.add(itemExit);
        
        menuNav.add(itemHome);
        menuNav.add(itemCari);
        menuNav.add(itemRiwayat);
        
        menuBar.add(menuFile);
        menuBar.add(menuNav);
        menuBar.add(menuAkun);
        setJMenuBar(menuBar);

        cardLayout = new CardLayout();
        mainPanel = new JPanel(cardLayout);

        mainPanel.add(new WelcomePanel(), "welcome");
        mainPanel.add(new SearchRoomPanel(), "search");
        mainPanel.add(new AdminRoomPanel(), "admin");
        mainPanel.add(new MyReservationsPanel(), "history");
        mainPanel.add(new AdminUserPanel(), "adminUser");

        add(mainPanel);
        cardLayout.show(mainPanel, "welcome");
    }

    public void showSearchPanel() { cardLayout.show(mainPanel, "search"); }
    public void showWelcomePanel() { cardLayout.show(mainPanel, "welcome"); }
    public void showHistoryPanel() { cardLayout.show(mainPanel, "history"); }
    
    public void showAdminRoomPanel() { cardLayout.show(mainPanel, "admin"); }
    public void showAdminUserPanel() { cardLayout.show(mainPanel, "adminUser"); }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.CardLayout());

        jMenu1.setText("File");

        jMenuItem1.setText("Keluar");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Reservasi");

        jMenuItem2.setText("Cari Kamar");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Riwayat");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Akun");

        jMenuItem4.setText("Logout");
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(377, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
